//
// Created by kotaru on 6/30/22.
//

#ifndef NONLINEAR_CONTROLS_INCLUDE_COMMON_OSQP_EIGEN_H
#define NONLINEAR_CONTROLS_INCLUDE_COMMON_OSQP_EIGEN_H

#endif //NONLINEAR_CONTROLS_INCLUDE_COMMON_OSQP_EIGEN_H
